[package]
name = "ray_marching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elsa = "1.9.0"
indicatif = "0.17.7"
minifb = "0.25.0"
